name: Deploy Weather Pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'producer/produce_weather.py'
      - 'validation/validate_weather.py'
  workflow_dispatch: # Allows manual "Run workflow" button click

permissions:
  id-token: write   # Required for OIDC handshake
  contents: read    # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Deploy Producer Lambda
        run: |
          # Zip the producer file (junking the folder path)
          zip -j producer.zip producer/produce_weather.py
          
          # Update the Producer Lambda
          aws lambda update-function-code \
            --function-name produce_weather \
            --zip-file fileb://producer.zip

      - name: Deploy Validator Lambda
        run: |
          # Zip the validator file (junking the folder path)
          zip -j validator.zip validation/validate_weather.py
          
          # Update the Validator Lambda
          aws lambda update-function-code \
            --function-name validate_weather \
            --zip-file fileb://validator.zip
